//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendApplication
{
    using FriendApplication.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Friend
    {
        [Display(Name = "Friend Id")]
        public int Id { get; set; }

        [StringLength(30, MinimumLength = 1)]
        [Display(Name = "Friend Name"), CustomRequired]
        public string Name { get; set; }

        [StringLength(25), Required]
        public string Place { get; set; }
    }
}
